# Generated by Django 5.0.7 on 2024-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebStoreApp", "0002_cart_cartitem_cart_products_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="city",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="country",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="gender",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="person",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="personadress",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="productdepartment",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="productpackage",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="productunit",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="review",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="sale",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="state",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="stock",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_default",
            field=models.IntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                help_text="The default stock",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="stockinventory",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="stockinventory",
            name="inventory_type",
            field=models.IntegerField(
                choices=[(1, "Incoming"), (0, "Outgoing")],
                help_text="Type of stock inventory",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="active",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="verified_user",
            field=models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
        ),
    ]
