# Generated by Django 5.0.7 on 2024-07-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebStoreApp", "0004_alter_branch_root_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="product_category_id",
            field=models.ForeignKey(
                blank=True,
                help_text="The product category table id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WebStoreApp.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "active",
                    models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("caption", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
                (
                    "deleted_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="WebStoreApp.product",
                    ),
                ),
                (
                    "updated_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
