# Generated by Django 5.0.7 on 2024-07-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebStoreApp", "0005_alter_productcategory_product_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_default",
            field=models.IntegerField(
                choices=[(1, "yes"), (0, "no")],
                default=1,
                help_text="This is the default image?",
                max_length=1,
            ),
        ),
    ]
