# Generated by Django 5.0.7 on 2024-07-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebStoreApp", "0007_alter_productimage_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "active",
                    models.IntegerField(choices=[(1, "Yes"), (0, "No")], max_length=1),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Product price",
                        max_digits=60,
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.IntegerField(
                        choices=[(1, "yes"), (0, "no")],
                        default=0,
                        help_text="This is the default price?",
                        max_length=1,
                    ),
                ),
                (
                    "created_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
                (
                    "deleted_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="WebStoreApp.product",
                    ),
                ),
                (
                    "updated_by_user_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)s_set",
                        to="WebStoreApp.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
