# Generated by Django 5.0.7 on 2024-07-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebStoreApp", "0008_productprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="person_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons",
                to="WebStoreApp.person",
            ),
        ),
    ]
